[versions]
agp = "8.7.2"
gson = "2.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
okhttp = "4.12.0"
lombok = "1.18.36"
refreshLayoutKernel = "2.1.0"
refreshHeaderClassics = "2.1.0"
refreshFooterClassics = "2.1.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
fastjson = { module = "com.alibaba:fastjson", version = "2.0.57" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
refresh-footer-classics = { module = "io.github.scwang90:refresh-footer-classics", version.ref = "refreshFooterClassics" }
refresh-header-classics = { module = "io.github.scwang90:refresh-header-classics", version.ref = "refreshHeaderClassics" }
refresh-layout-kernel = { module = "io.github.scwang90:refresh-layout-kernel", version.ref = "refreshLayoutKernel" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

